/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,html}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#484848',
        'outline': '#757575',
        'error-container': '#9f0519',
        'error': '#ff716c',
        'surface-container-low': '#131313',
        'on-background': '#ffffff',
        'primary-fixed': '#00e3fd',
        'surface-bright': '#2c2c2c',
        'on-error-container': '#ffa8a3',
        'on-primary-fixed-variant': '#005762',
        'on-secondary-container': '#f8f7ff',
        'secondary-fixed': '#c4d0ff',
        'secondary-fixed-dim': '#b0c2ff',
        'tertiary-dim': '#ff68a8',
        'tertiary': '#ff68a8',
        'secondary': '#7799ff',
        'surface-container-lowest': '#000000',
        'on-tertiary-fixed-variant': '#750040',
        'primary-dim': '#00d4ec',
        'inverse-primary': '#006976',
        'tertiary-fixed': '#ff8db8',
        'inverse-surface': '#f9f9f9',
        'surface-container': '#191919',
        'primary-container': '#00e3fd',
        'on-tertiary-container': '#0f0005',
        'primary': '#81ecff',
        'on-primary-container': '#004d57',
        'secondary-dim': '#316bf3',
        'on-primary-fixed': '#003840',
        'surface-tint': '#81ecff',
        'error-dim': '#d7383b',
        'on-secondary-fixed-variant': '#0047bd',
        'secondary-container': '#0053db',
        'surface-dim': '#0e0e0e',
        'on-tertiary': '#460025',
        'on-surface': '#ffffff',
        'tertiary-fixed-dim': '#ff73ad',
        'on-secondary-fixed': '#002d80',
        'primary-fixed-dim': '#00d4ec',
        'on-primary': '#005762',
        'on-surface-variant': '#ababab',
        'surface': '#0e0e0e',
        'background': '#0e0e0e',
        'tertiary-container': '#ff3399',
        'surface-container-highest': '#262626',
        'inverse-on-surface': '#555555',
        'surface-variant': '#262626',
        'surface-container-high': '#1f1f1f',
        'on-error': '#490006',
        'on-tertiary-fixed': '#37001C',
        'on-secondary': '#001b55',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
